[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[[build.nixpacksPlan.phases.setup.aptPkgs]]
name = "tesseract-ocr"

[[build.nixpacksPlan.phases.setup.aptPkgs]]
name = "tesseract-ocr-por"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
